# Generated by Django 5.1.7 on 2025-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
